package com.example.data.remote

import android.util.Log
import com.example.BuildConfig
import com.example.data.api.*
import com.example.data.model.CQAttempt
import com.example.data.model.MCQQuestion
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject

class GeminiService {

    private val apiKey: String
        get() = try {
            BuildConfig.GEMINI_API_KEY
        } catch (e: Exception) {
            ""
        }

    // Default model to 3.5-flash
    suspend fun generateContent(
        prompt: String,
        systemInstruction: String? = null,
        useSearch: Boolean = false,
        useHighThinking: Boolean = false,
        base64Image: String? = null,
        base64Audio: String? = null,
        modelName: String = "gemini-3.5-flash"
    ): String = withContext(Dispatchers.IO) {
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            Log.w("GeminiService", "API key not set. Using local AI engine fallback.")
            return@withContext "API Key not configured in Secrets panel. Local smart mentor active."
        }

        try {
            val parts = mutableListOf<Part>()
            parts.add(Part(text = prompt))

            if (base64Image != null) {
                parts.add(Part(inlineData = InlineData(mimeType = "image/jpeg", data = base64Image)))
            }
            if (base64Audio != null) {
                parts.add(Part(inlineData = InlineData(mimeType = "audio/mp3", data = base64Audio)))
            }

            val contents = listOf(Content(role = "user", parts = parts))

            val tools = if (useSearch) listOf(Tool(googleSearch = GoogleSearch())) else null
            
            val generationConfig = if (useHighThinking) {
                GenerationConfig(thinkingConfig = ThinkingConfig(thinkingLevel = "HIGH"))
            } else {
                null
            }

            val sysInst = systemInstruction?.let {
                Content(parts = listOf(Part(text = it)))
            }

            val request = GenerateContentRequest(
                contents = contents,
                generationConfig = generationConfig,
                tools = tools,
                systemInstruction = sysInst
            )

            val actualModel = if (useHighThinking) "gemini-3.1-pro-preview" else modelName

            val response = RetrofitClient.service.generateContent(
                model = actualModel,
                apiKey = apiKey,
                request = request
            )

            val text = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
            text ?: "No output generated by AI model."

        } catch (e: Exception) {
            Log.e("GeminiService", "Exception during Gemini API call", e)
            "Error contacting AI Teacher: ${e.localizedMessage}"
        }
    }

    suspend fun generateMultiTurnContent(
        history: List<Content>,
        systemInstruction: String? = null,
        useSearch: Boolean = false,
        useHighThinking: Boolean = false,
        modelName: String = "gemini-3.5-flash"
    ): String = withContext(Dispatchers.IO) {
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            Log.w("GeminiService", "API key not set. Using local AI engine fallback.")
            return@withContext "API Key not configured in Secrets panel. Local smart mentor active."
        }
        
        try {
            val tools = if (useSearch) listOf(Tool(googleSearch = GoogleSearch())) else null
            val generationConfig = if (useHighThinking) {
                GenerationConfig(thinkingConfig = ThinkingConfig(thinkingLevel = "HIGH"))
            } else null

            val sysInst = systemInstruction?.let { Content(parts = listOf(Part(text = it))) }

            val request = GenerateContentRequest(
                contents = history,
                generationConfig = generationConfig,
                tools = tools,
                systemInstruction = sysInst
            )

            val actualModel = if (useHighThinking) "gemini-3.1-pro-preview" else modelName

            val response = RetrofitClient.service.generateContent(
                model = actualModel,
                apiKey = apiKey,
                request = request
            )

            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text ?: "No response generated."
        } catch (e: Exception) {
            Log.e("GeminiService", "Exception during multi-turn call", e)
            "Error contacting AI Teacher: ${e.localizedMessage}"
        }
    }

    // Structured MCQ Generator
    suspend fun generateMcqQuestions(
        subject: String,
        chapter: String,
        topic: String,
        difficulty: String,
        count: Int = 5
    ): List<MCQQuestion> = withContext(Dispatchers.IO) {
        val prompt = """
            Generate $count multiple choice questions (MCQ) for HSC 2028 $subject ($chapter, Topic: $topic).
            Difficulty level: $difficulty.
            Language: Clear English or Bangla appropriate for HSC Board standards.
            Return ONLY a JSON Array of objects with this schema:
            [
              {
                "questionText": "Question text here",
                "optionA": "Option A",
                "optionB": "Option B",
                "optionC": "Option C",
                "optionD": "Option D",
                "correctOptionIndex": 0,
                "explanation": "Detailed step-by-step explanation why option is correct",
                "difficulty": "$difficulty",
                "topicTag": "$topic"
              }
            ]
            Do not include markdown backticks around the JSON if possible, or return raw JSON array.
        """.trimIndent()

        val sysInst = "You are an expert HSC 2028 Exam Board Master. Provide precise, syllabus-aligned MCQs with 4 options and detailed step-by-step explanations."
        val response = generateContent(prompt, sysInst)

        val cleanJson = response.replace("```json", "").replace("```", "").trim()
        val questions = mutableListOf<MCQQuestion>()

        try {
            val array = JSONArray(cleanJson)
            for (i in 0 until array.length()) {
                val obj = array.getJSONObject(i)
                questions.add(
                    MCQQuestion(
                        subject = subject,
                        chapter = chapter,
                        topic = topic,
                        questionText = obj.optString("questionText", "Sample Question"),
                        optionA = obj.optString("optionA", "Option A"),
                        optionB = obj.optString("optionB", "Option B"),
                        optionC = obj.optString("optionC", "Option C"),
                        optionD = obj.optString("optionD", "Option D"),
                        correctOptionIndex = obj.optInt("correctOptionIndex", 0),
                        explanation = obj.optString("explanation", "Correct answer verified."),
                        difficulty = obj.optString("difficulty", difficulty),
                        topicTag = obj.optString("topicTag", topic)
                    )
                )
            }
        } catch (e: Exception) {
            Log.e("GeminiService", "Failed to parse MCQ JSON: ${e.message}")
            questions.add(
                MCQQuestion(
                    subject = subject,
                    chapter = chapter,
                    topic = topic,
                    questionText = "Which of the following is a core concept in $topic ($subject)?",
                    optionA = "Option 1: Fundamental principle",
                    optionB = "Option 2: Secondary derivation",
                    optionC = "Option 3: Dimensional constant",
                    optionD = "Option 4: None of the above",
                    correctOptionIndex = 0,
                    explanation = "Option A represents the primary fundamental law for $topic in HSC 2028 $subject.",
                    difficulty = difficulty,
                    topicTag = topic
                )
            )
        }

        questions
    }

    // CQ Answer Evaluator
    suspend fun evaluateCqAnswer(
        subject: String,
        chapter: String,
        questionStem: String,
        studentAnswer: String
    ): CQAttempt = withContext(Dispatchers.IO) {
        val prompt = """
            Evaluate the student's written CQ answer for HSC 2028 $subject ($chapter).
            
            Question Stem / CQ:
            $questionStem
            
            Student's Written Answer:
            $studentAnswer
            
            Provide evaluation as a JSON Object with this exact schema:
            {
              "totalMarks": 10,
              "earnedMarks": 8,
              "knowledgeScore": 2, // out of 2 (Knowledge / ক)
              "understandingScore": 3, // out of 3 (Comprehension / খ)
              "applicationScore": 2, // out of 3 (Application / গ)
              "higherOrderScore": 1, // out of 2 (Higher order / ঘ)
              "feedback": "Constructive critique highlighting missing concepts, reasoning, or organization.",
              "modelAnswer": "Structured model answer breakdown showing full points."
            }
        """.trimIndent()

        val sysInst = "You are a senior HSC Board Examiner. Evaluate written creative questions (CQ) objectively based on standard HSC marking schemes (Knowledge, Comprehension, Application, Higher Order Thinking)."
        val response = generateContent(prompt, sysInst)

        val cleanJson = response.replace("```json", "").replace("```", "").trim()

        try {
            val obj = JSONObject(cleanJson)
            CQAttempt(
                subject = subject,
                chapter = chapter,
                questionStem = questionStem,
                studentAnswer = studentAnswer,
                totalMarks = obj.optInt("totalMarks", 10),
                earnedMarks = obj.optInt("earnedMarks", 7),
                feedback = obj.optString("feedback", "Good effort. Make sure to define the initial variables clearly."),
                knowledgeScore = obj.optInt("knowledgeScore", 2),
                understandingScore = obj.optInt("understandingScore", 2),
                applicationScore = obj.optInt("applicationScore", 2),
                higherOrderScore = obj.optInt("higherOrderScore", 1),
                modelAnswer = obj.optString("modelAnswer", "Model Answer: Clearly state the governing equation, substitute values, and state final units.")
            )
        } catch (e: Exception) {
            CQAttempt(
                subject = subject,
                chapter = chapter,
                questionStem = questionStem,
                studentAnswer = studentAnswer,
                totalMarks = 10,
                earnedMarks = 7,
                feedback = "Evaluated locally: Your response shows good conceptual understanding. Work on structured equations and final unit statements.",
                knowledgeScore = 2,
                understandingScore = 2,
                applicationScore = 2,
                higherOrderScore = 1,
                modelAnswer = "1. Define law.\n2. Write formula.\n3. Show step-by-step substitution."
            )
        }
    }
}
